# Generated by Django 5.1.1 on 2024-09-30 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='busowner_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('license', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='route_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_rout', models.CharField(max_length=100)),
                ('to_rout', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bus_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regno', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('insurance', models.BigIntegerField()),
                ('rcbook', models.CharField(max_length=100)),
                ('bus_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.busowner_table')),
            ],
        ),
        migrations.CreateModel(
            name='assign_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.bus_table')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.employee_table')),
            ],
        ),
        migrations.AddField(
            model_name='employee_table',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.login_table'),
        ),
        migrations.AddField(
            model_name='busowner_table',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.login_table'),
        ),
        migrations.CreateModel(
            name='stop_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fair', models.BigIntegerField()),
                ('stage', models.BigIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.route_table')),
            ],
        ),
        migrations.CreateModel(
            name='trip_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.login_table')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.route_table')),
            ],
        ),
        migrations.CreateModel(
            name='timing_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.stop_table')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.trip_table')),
            ],
        ),
        migrations.CreateModel(
            name='collection_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.trip_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.bus_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.bus_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('from_booking', models.CharField(max_length=100)),
                ('to_booking', models.CharField(max_length=100)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.trip_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.user_table')),
            ],
        ),
    ]
