# Generated by Django 5.1.1 on 2024-11-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0002_alter_notification_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_table',
            name='fitness',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
