# Generated by Django 5.1.1 on 2024-11-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0003_bus_table_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_table',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buss.bus_table'),
        ),
    ]
