# Generated by Django 5.1.1 on 2024-11-19 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0004_alter_trip_table_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_table',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buss.busowner_table'),
            preserve_default=False,
        ),
    ]
