# Generated by Django 5.1.1 on 2024-11-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buss', '0005_employee_table_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_table',
            name='regno',
            field=models.CharField(max_length=20),
        ),
    ]
